name: "Frogbot Pull Request Scan"
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    # ADD THIS LINE BELOW
    environment: production 
    
    env:
      # Add the trailing slash / to match your working deploy.yml exactly
      JF_URL: https://${{ vars.JF_URL }}/
      JF_OIDC_PROVIDER_NAME: hs-gh
      JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Frogbot
        uses: jfrog/frogbot@v2
        with:
          oidc-provider-name: hs-gh
